// templates/react/src/App.jsx
import { useRef, useEffect } from 'react'
import mapboxgl from 'mapbox-gl'

import 'mapbox-gl/dist/mapbox-gl.css';
import './App.css'

function App() {

  const mapRef = useRef()
  const mapContainerRef = useRef()

  useEffect(() => {
     mapRef.current = new mapboxgl.Map({
      accessToken: import.meta.env.VITE_MAPBOX_ACCESS_TOKEN,
      container: mapContainerRef.current,
      style: 'mapbox://styles/mapbox/standard',
      center:  [-71.05953, 42.36290],
      zoom: 13,
    });

    return () => {
      mapRef.current.remove()
    }
  }, [])


return (
  <>
    <div id='map-container' ref={mapContainerRef} />
  </>
  )
}

export default App

// templates/svelte/src/App.svelte
<script>
  import { Map } from 'mapbox-gl';
  import 'mapbox-gl/dist/mapbox-gl.css';
  import { onMount, onDestroy } from 'svelte';

  let map;
  let mapContainer;


  onMount(() => {
    map = new Map({
      container: mapContainer,
      accessToken: import.meta.env.VITE_MAPBOX_ACCESS_TOKEN,
      style: 'mapbox://styles/mapbox/standard',
      center: [-71.05953, 42.36290],
      zoom: 13
    });
    
  });

  onDestroy(() => {
    map.remove();
  });

</script>
<div class="map" bind:this={mapContainer}></div> 


<style>
  .map {
    position: absolute;
    width: 100%;
    height: 100%;
  }
</style>
