// templates/shared/search-enabled-apps/svelte/src/App.svelte
<script>
  import mapboxgl from 'mapbox-gl'
  import 'mapbox-gl/dist/mapbox-gl.css';
  import { onMount, onDestroy } from 'svelte';
  import { MapboxSearchBox } from '@mapbox/search-js-web';

  let map;
  let mapContainer;
  let accessToken = import.meta.env.VITE_MAPBOX_ACCESS_TOKEN;

  onMount(() => {
    map = new mapboxgl.Map({
      container: mapContainer,
      accessToken,
      style: 'mapbox://styles/mapbox/standard',
      center: [-71.05953, 42.36290],
      zoom: 13
    });

    map.on('load', () => {
      const searchBox = new MapboxSearchBox();
      searchBox.accessToken = accessToken;
      searchBox.options = {
        proximity: [-71.05953, 42.36290]
      };
      searchBox.marker = true;
      searchBox.mapboxgl = mapboxgl;
      searchBox.componentOptions = { 
        allowReverse: true, 
        flipCoordinates: true 
      };
      
      map.addControl(searchBox);
    });
  });

  onDestroy(() => {
    if (map) {
      map.remove();
    }
  });

</script>
<div class="map" bind:this={mapContainer}></div> 


<style>
  .map {
    position: absolute;
    width: 100%;
    height: 100%;
  }
</style>

// templates/shared/search-enabled-apps/react-ts/App.tsx
import { useRef, useEffect, useState } from 'react'
import mapboxgl from 'mapbox-gl'
import { SearchBox } from '@mapbox/search-js-react'

import 'mapbox-gl/dist/mapbox-gl.css'
import './App.css'

const accessToken = import.meta.env.VITE_MAPBOX_ACCESS_TOKEN
const center:[number, number] = [-71.05953, 42.36290]

function App() {
  const mapRef = useRef<mapboxgl.Map | null>(null)
  const mapContainerRef = useRef<HTMLDivElement>(null)
  const [inputValue, setInputValue] = useState('')

  useEffect(() => {
    mapRef.current = new mapboxgl.Map({
      accessToken,
      style: 'mapbox://styles/mapbox/standard',
      container: mapContainerRef.current!,
      center,
      zoom: 13,
    })

    return () => {
      mapRef.current?.remove()
    }
  }, [])

  return (
    <>
        <div style={{
            margin: '10px 10px 0 0',
            width: 300,
            right: 0,
            top: 0,
            position: 'absolute',
            zIndex: 10 }}>
            <SearchBox 
                accessToken={accessToken}
                map={mapRef.current}
                mapboxgl={mapboxgl}
                value={inputValue}
                options={{
                  proximity: center
                }}
                onChange={(d) => {
                    setInputValue(d);
                }}
                marker
            />
        </div>
        <div id='map-container' ref={mapContainerRef} />
    </>
  )
}

export default App
